Capa_Presentacion/Controllers/TransaccionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Capa_Entidaddes;
using Capa_Negocio;
using System.Web.Mvc;

namespace Capa_Presentacion.Controllers
{
    public class TransaccionController : Controller
    {
        // GET: Transaccion
        private readonly TransaccionNegocio _negocio;

        public TransaccionController()
        {
            _negocio = new TransaccionNegocio();
        }

        // GET: Transaccion
        public ActionResult Index()
        {
            var leer = _negocio.leer();
            return View(leer);
        }

        //Crear Empleeado
        public ActionResult Crear()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Crear(Transaccion transaccion)
        {
            _negocio.TransaccionsCrear(transaccion);
            return RedirectToAction(nameof(Index));
        }

        //Editar Empleeado
        [HttpGet]
        public ActionResult Editar(int id)
        {
            var transaccion = _negocio.GetTransaccion(id);

            if (transaccion == null)
            {
                return null;
            }

            return View(transaccion);
        }

        [HttpPost]
        public ActionResult Editar(Transaccion transaccion)
        {
            if (ModelState.IsValid)
            {
                _negocio.Editar(transaccion);
                return RedirectToAction(nameof(Index));
            }

            return View(transaccion);
        }

        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            var transaccion = _negocio.GetTransaccion(id);

            if (transaccion == null)
            {
                return null;
            }

            return View(transaccion);
        }

        [HttpPost]
        public ActionResult Eliminar(Transaccion transaccion)
        {
            if (ModelState.IsValid)
            {
                _negocio.Eliminar(transaccion);
                return RedirectToAction(nameof(Index));
            }

            return View();
        }
    }
}

Capa_Presentacion/Views/Transaccion/Crear.cshtml
@model Capa_Entidaddes.Transaccion

@{
    ViewBag.Title = "Crear";
}

<h2>Crear</h2>
<link href="~/Content/Table.css" rel="stylesheet" />
<link href="~/Content/Crear.css" rel="stylesheet" />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Transaccion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Tipo_Transaccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID_Tipo_Transaccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID_Tipo_Transaccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estatus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index","Transaccion", new {@class="btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Capa_Presentacion/Views/Transaccion/Editar.cshtml
@model Capa_Entidaddes.Transaccion

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

<link href="~/Content/Table.css" rel="stylesheet" />
<link href="~/Content/Crear.css" rel="stylesheet" />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Transaccion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID_Transaccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID_Transaccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID_Transaccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Tipo_Transaccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID_Tipo_Transaccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID_Tipo_Transaccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estatus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
    <input type="hidden" id="ID_Transaccion" name="ID_Transaccion" value="@Model.ID_Transaccion" />

}

<div>
    @Html.ActionLink("Back to List", "Index","Transaccion",new {@class="btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Capa_Presentacion/Views/Transaccion/Eliminar.cshtml
@model Capa_Entidaddes.Transaccion

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar</h2>
<link href="~/Content/Table.css" rel="stylesheet" />
<link href="~/Content/Crear.css" rel="stylesheet" />
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Transaccion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID_Transaccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID_Transaccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ID_Tipo_Transaccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID_Tipo_Transaccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estatus)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <input type="hidden" value="@Model.ID_Transaccion" id="ID_Transaccion" name="ID_Transaccion" />

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index","Transaccion",new {@class="btn btn-primary" })
        </div>
    }
</div>

Capa_Presentacion/Views/Transaccion/Index.cshtml
@model IEnumerable<Capa_Entidaddes.Transaccion>

@{
    ViewBag.Title = "Index";
}

<h2>Lista de Transacciones </h2>
<link href="~/Content/Table.css" rel="stylesheet" />
<p>
    @Html.ActionLink("Nueva Transacion",  // texto
                 "Crear", // action
                 "Transaccion",  // controlador
                 new { @class = "btn btn-success" }) // html attributes
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ID_Transaccion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ID_Tipo_Transaccion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estatus)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ID_Transaccion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ID_Tipo_Transaccion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estatus)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new { id=item.ID_Transaccion  }, new { @class = "btn btn-primary" }) |
            @Html.ActionLink("Eliminar", "Eliminar", new { id = item.ID_Transaccion }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>