Capa_Presentacion/Controllers/EmpleadoController.cs
using Capa_Entidaddes;
using Capa_Negocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Capa_Presentacion.Controllers
{
    public class EmpleadoController : Controller
    {
        private readonly EmpleadosNegocio _negocio;

        public EmpleadoController()
        {
            _negocio = new EmpleadosNegocio();
        }

        // GET: Empleado
        public ActionResult Index()
        {
            var leer = _negocio.leer();
            return View(leer);
        }

        //Crear Empleeado
        public ActionResult Crear()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Crear(Empleado empleado)
        {
            _negocio.EmpleadosCrear(empleado);
            return RedirectToAction(nameof(Index));
        }

        //Editar Empleeado
        [HttpGet]
        public ActionResult Editar(int id)
        {
            var empleado = _negocio.GetEmpleado(id);

            if (empleado == null)
            {
                return null;
            }

            return View(empleado);
        }

        [HttpPost]
        public ActionResult Editar(Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                _negocio.Editar(empleado);
                return RedirectToAction(nameof(Index));
            }

            return View(empleado);
        }

        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            var empleado = _negocio.GetEmpleado(id);

            if (empleado == null)
            {
                return null;
            }

            return View(empleado);
        }

        [HttpPost]
        public ActionResult Eliminar(Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                _negocio.Eliminar(empleado);
                return RedirectToAction(nameof(Index));
            }

            return View();
        }
    }
}

Capa_Presentacion/Views/Empleado/Crear.cshtml
@model Capa_Entidaddes.Empleado

@{
    ViewBag.Title = "Crear";
}

<h2>Crear</h2>

<link href="~/Content/Table.css" rel="stylesheet" />
<link href="~/Content/Crear.css" rel="stylesheet" />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Empleado</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cedula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cedula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Empleado_Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Empleado_Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Empleado_Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Id_Depart6amento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id_Depart6amento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id_Depart6amento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Id_Puesto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id_Puesto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id_Puesto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Igreso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID_Igreso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID_Igreso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index", "Empleado", new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Capa_Presentacion/Views/Empleado/Editar.cshtml
@model Capa_Entidaddes.Empleado

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>
<link href="~/Content/Table.css" rel="stylesheet" />
<link href="~/Content/Crear.css" rel="stylesheet" />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Empleado</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cedula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cedula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Empleado_Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Empleado_Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Empleado_Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Id_Depart6amento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id_Depart6amento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id_Depart6amento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Id_Puesto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id_Puesto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id_Puesto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Igreso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID_Igreso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID_Igreso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>

    <input type="hidden" id="ID_Empleado" name="ID_Empleado" value="@Model.ID_Empleado" />
}

<div>
    @Html.ActionLink("Regresar", "Index","Empleado", new {@class="btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Capa_Presentacion/Views/Empleado/Eliminar.cshtml
@model Capa_Entidaddes.Empleado

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar</h2>
<link href="~/Content/Table.css" rel="stylesheet" />
<link href="~/Content/Crear.css" rel="stylesheet" />
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID_Empleado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID_Empleado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cedula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cedula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Empleado_Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empleado_Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Id_Depart6amento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id_Depart6amento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Id_Puesto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id_Puesto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ID_Igreso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID_Igreso)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <input type="hidden" value="@Model.ID_Empleado" id="ID_Empleado" name="ID_Empleado" />
        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-danger" /> |
            @Html.ActionLink("Regresar", "Index","Empleado",new { @class = "btn btn-primary" })
        </div>
    }
</div>

Capa_Presentacion/Views/Empleado/Index.cshtml
@model IEnumerable<Capa_Entidaddes.Empleado>

@{
    ViewBag.Title = "Index";
}


<!DOCTYPE html>
<html>
<head>
    <title></title>
    <link href="~/Content/Table.css" rel="stylesheet" />
</head>
<body>
    <h2>Listado De Empleados</h2>
    <p>
        @Html.ActionLink("Nuevo Empleado", "Crear","Empleado", new {@class="btn btn-success" })
    </p>


    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID_Empleado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cedula)
            </th>
            <th>
                Nombre del Empleado
            </th>
            <th>
                Departamento
            </th>
            <th>
                Puesto
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ID_Igreso)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ID_Empleado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cedula)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Empleado_Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Id_Depart6amento)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Id_Puesto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Salario)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ID_Igreso)
                </td>
                <td>

                    @Html.ActionLink("Editar", "Editar", new { id = item.ID_Empleado }, new {@class="btn btn-primary" }) |
                    @Html.ActionLink("Eliminar", "Eliminar", new { id = item.ID_Empleado }, new {@class="btn btn-danger" })
                </td>
            </tr>
        }

    </table>
</body>
</html>