Capa_Presentacion/Controllers/Tipo_IngresoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Capa_Negocio;
using Capa_Entidaddes;
using System.Web;
using System.Web.Mvc;

namespace Capa_Presentacion.Controllers
{
    public class tipo_IngresoController : Controller
    {
        // GET: Yipo_Ingreso
        private readonly NegocioTipo_Ingreso _negocio;

        public tipo_IngresoController()
        {
            _negocio = new NegocioTipo_Ingreso();
        }

        // GET: Tipo_Ingreso
        public ActionResult Index()
        {
            var leer = _negocio.leer();
            return View(leer);
        }

        //Crear Empleeado
        public ActionResult Crear()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Crear(Tipos_Ingresos Tipo_Ingreso)
        {
            _negocio.EmpleadosCrear(Tipo_Ingreso);
            return View();
        }

        //Editar Empleeado
        [HttpGet]
        public ActionResult Editar(int id)
        {
            var Tipo_Ingreso = _negocio.GetTipos_Ingresos(id);

            if (Tipo_Ingreso == null)
            {
                return null;
            }

            return View(Tipo_Ingreso);
        }

        [HttpPost]
        public ActionResult Editar(Tipos_Ingresos Tipo_Ingreso)
        {
            if (ModelState.IsValid)
            {
                _negocio.Editar(Tipo_Ingreso);
                return RedirectToAction(nameof(Index));
            }

            return View(Tipo_Ingreso);
        }

        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            var Tipo_Ingreso = _negocio.GetTipos_Ingresos(id);

            if (Tipo_Ingreso == null)
            {
                return null;
            }

            return View(Tipo_Ingreso);
        }

        [HttpPost]
        public ActionResult Eliminar(Tipos_Ingresos Tipo_Ingreso)
        {
            if (ModelState.IsValid)
            {
                _negocio.Eliminar(Tipo_Ingreso);
                return RedirectToAction(nameof(Index));
            }

            return View();
        }
    }
}

Capa_Presentacion/Views/tipo_Ingreso/Crear.cshtml
@model Capa_Entidaddes.Tipos_Ingresos

@{
    ViewBag.Title = "Crear";
}

<h2>Crear</h2>
<link href="~/Content/Table.css" rel="stylesheet" />
<link href="~/Content/Crear.css" rel="stylesheet" />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Ingresos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salario_estandar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salario_estandar, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salario_estandar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index","tipos_ingresos", new {@class="btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Capa_Presentacion/Views/tipo_Ingreso/Editar.cshtml
@model Capa_Entidaddes.Tipos_Ingresos

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>
<link href="~/Content/Table.css" rel="stylesheet" />
<link href="~/Content/Crear.css" rel="stylesheet" />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Tipos Ingresos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID_Ingresos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID_Ingresos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID_Ingresos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salario_estandar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salario_estandar, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salario_estandar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>

    <input type="hidden" value="@Model.ID_Ingresos" id="ID_Empleado" name="ID_Ingresos" />

}

<div>
    @Html.ActionLink("Back to List", "Index","tipo_Ingreso",new {@class="btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Capa_Presentacion/Views/tipo_Ingreso/Eliminar.cshtml
@model Capa_Entidaddes.Tipos_Ingresos

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar</h2>
<link href="~/Content/Table.css" rel="stylesheet" />
<link href="~/Content/Crear.css" rel="stylesheet" />
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tipos Ingresos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID_Ingresos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID_Ingresos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salario_estandar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salario_estandar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <input type="hidden" value="@Model.ID_Ingresos" id="ID_Ingresos" name="ID_Ingresos" />

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index","tipo_Ingreso",new {@class="btn btn-primary" })
        </div>
    }
</div>

Capa_Presentacion/Views/tipo_Ingreso/Index.cshtml
@model IEnumerable<Capa_Entidaddes.Tipos_Ingresos>

@{
    ViewBag.Title = "Index";
}

<h2>Lista de Ingresos</h2>
<link href="~/Content/Table.css" rel="stylesheet" />
<p>
    @Html.ActionLink("Nuevo Ingreso", "Crear", "Tipo_Ingreso", new {@class="btn btn-success" })
</p>.
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ID_Ingresos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salario_estandar)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estado)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ID_Ingresos)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Salario_estandar)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estado)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new {  id=item.ID_Ingresos  }, new {@class="btn btn-primary" }) |
            @Html.ActionLink("Eliminar", "Eliminar", new { id = item.ID_Ingresos }, new {@class="btn btn-danger" })
        </td>
    </tr>
}

</table>