Capa_Presentacion/Controllers/PuestoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Capa_Entidaddes;
using Capa_Negocio;
using System.Web.Mvc;

namespace Capa_Presentacion.Controllers
{
    public class PuestoController : Controller
    {
        // GET: Puesto
        private readonly PuestoNegocio _negocio;

        public PuestoController()
        {
            _negocio = new PuestoNegocio();
        }

        // GET: Empleado
        public ActionResult Index()
        {
            var leer = _negocio.leer();
            return View(leer);
        }

        //Crear Puesto
        public ActionResult Crear()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Crear(Puesto puesto)
        {
            _negocio.puestoCrear(puesto);
            return RedirectToAction(nameof(Index));
        }

        //Editar Puesto
        [HttpGet]
        public ActionResult Editar(int id)
        {
            var puesto = _negocio.Getpuesto(id);

            if (puesto == null)
            {
                return null;
            }

            return View(puesto);
        }

        [HttpPost]
        public ActionResult Editar(Puesto puesto)
        {
            if (ModelState.IsValid)
            {
                _negocio.Editar(puesto);
                return RedirectToAction(nameof(Index));

            }

            return View(puesto);
        }

        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            var puesto = _negocio.Getpuesto(id);

            if (puesto == null)
            {
                return null;
            }

            return View(puesto);
        }

        [HttpPost]
        public ActionResult Eliminar(Puesto puesto)
        {
            if (ModelState.IsValid)
            {
                _negocio.Eliminar(puesto);
                return RedirectToAction(nameof(Index));
            }

            return View();
        }
    }
}

Capa_Presentacion/Views/Puesto/Crear.cshtml
@model Capa_Entidaddes.Puesto

@{
    ViewBag.Title = "Crear";
}

<h2>Crear</h2>
<link href="~/Content/Table.css" rel="stylesheet" />
<link href="~/Content/Crear.css" rel="stylesheet" />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Puesto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rango, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rango, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rango, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Saldo_Minimo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Saldo_Minimo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Saldo_Minimo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Saldo_Maximo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Saldo_Maximo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Saldo_Maximo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index","Puesto", new {@class="btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Capa_Presentacion/Views/Puesto/Editar.cshtml
@model Capa_Entidaddes.Puesto

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>
<link href="~/Content/Table.css" rel="stylesheet" />
<link href="~/Content/Crear.css" rel="stylesheet" />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Puesto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rango, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rango, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rango, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Saldo_Minimo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Saldo_Minimo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Saldo_Minimo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Saldo_Maximo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Saldo_Maximo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Saldo_Maximo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
    <input type="hidden" id="ID_Puesto" name="ID_Puesto" value="@Model.ID_Puesto" />


}

<div>
    @Html.ActionLink("Back to List", "Index", "Puesto", new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Capa_Presentacion/Views/Puesto/Eliminar.cshtml
@model Capa_Entidaddes.Puesto

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar</h2>
<link href="~/Content/Table.css" rel="stylesheet" />
<link href="~/Content/Crear.css" rel="stylesheet" />
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Puesto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID_Puesto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID_Puesto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rango)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rango)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Saldo_Minimo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Saldo_Minimo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Saldo_Maximo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Saldo_Maximo)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <input type="hidden" value="@Model.ID_Puesto" id="ID_Puesto" name="ID_Puesto" />

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index","Puesto",new {@class="btn btn-primary" })
        </div>
    }
</div>

Capa_Presentacion/Views/Puesto/Index.cshtml
@model IEnumerable<Capa_Entidaddes.Puesto>

@{
    ViewBag.Title = "Index";
}

<h2>Lista de Puesto</h2>
<link href="~/Content/Table.css" rel="stylesheet" />
<p>
    @Html.ActionLink("Nuevo Puesto", "Crear", "Puesto", new {@class="btn btn-success" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ID_Puesto)
        </th>
        <th>
            Nombre
        </th>
        <th>
            Rango
        </th>
        <th>
            Saldo Minimo
        </th>
        <th>
            Saldo Maximo
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ID_Puesto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rango)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Saldo_Minimo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Saldo_Maximo)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new { id=item.ID_Puesto  }, new {@class="btn btn-primary" }) |
            @Html.ActionLink("Delete", "Eliminar", new {  id=item.ID_Puesto  }, new {@class="btn btn-danger" })
        </td>
    </tr>
}

</table>